### ISSUE TITLE
module_column部分关键字段用bit类型导致配置读取不出来

### ISSUE THREAD

**Issue by SpecialCyCi** [rockefys/commlib#1]
module_column 是否插入等字段用了bit，在WINDOWS，MAC环境下均读取不到字段数值出来，导致完全没有办法使用代码生成，改为smallint就ok了，建议使用smallint 类型。
希望作者能继续完善项目。

**Comment by sitez** [comment]
download zip后为何无法打开呢

**Comment by SpecialCyCi** [comment]
这个你可以直接git clone啊...

**Comment by rockefys** [comment]
Fixed yet ,thks .
